import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import AppLayout from '../../components/AppLayout'
import PriorityBadge from '../../components/PriorityBadge'
import StatusBadge from '../../components/StatusBadge'
import { useAuth } from '../../context/AuthContext'
import { formatDateTime, getIssues, saveIssues } from '../../data/demoStore'
import { useDemoData } from '../../context/useDemoData'
function IssueDetails() { const { id }=useParams(); const {currentUser}=useAuth(); const issue=useDemoData('issues').find(x=>x.id===id&&x.assignedTo===currentUser.id); const [note,setNote]=useState(''); if(!issue)return <AppLayout><p>Issue not found. <Link className="text-emerald-700 underline" to="/staff/issues">Back to assigned issues</Link></p></AppLayout>; function update(status){saveIssues(getIssues().map(x=>x.id===id?{...x,status,resolutionNote:note||x.resolutionNote,statusHistory:[...x.statusHistory,{status,by:currentUser.name,date:formatDateTime()}]}:x));setNote('')} return <AppLayout><div className="mx-auto max-w-4xl"><Link className="text-sm font-bold text-emerald-700" to="/staff/issues">← Assigned Issues</Link><article className="mt-4 rounded-xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-slate-500">{issue.id} · {issue.category}</p><h1 className="text-3xl font-bold text-slate-900">{issue.title}</h1></div><div className="flex gap-2"><PriorityBadge priority={issue.priority}/><StatusBadge status={issue.status}/></div></div><p className="mt-5 text-slate-600">{issue.description}</p><p className="mt-3 text-sm text-slate-500">{issue.location} · Reported by {issue.reporter}</p></article><section className="mt-6 rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Update Issue</h2><textarea className="mt-4 w-full rounded-lg border p-3 text-sm" value={note} onChange={e=>setNote(e.target.value)} placeholder="Add resolution notes" rows="4"/><div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>update('In Progress')} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white">Mark In Progress</button><button onClick={()=>update('Resolved')} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold text-white">Mark Resolved</button></div></section><section className="mt-6 rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">History</h2>{issue.statusHistory.map((x,i)=><p className="mt-3 text-sm text-slate-600" key={i}><strong>{x.status}</strong> · {x.by} · {x.date}</p>)}</section></div></AppLayout> }
export default IssueDetails
