import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import AppLayout from '../../components/AppLayout'
import { useAuth } from '../../context/AuthContext'
import { formatDate, formatDateTime, getIssues, saveIssues } from '../../data/demoStore'
import { useDemoData } from '../../context/useDemoData'

const input = 'w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100'
function ReportIssue() {
  const { currentUser } = useAuth(); const categories = useDemoData('categories'); const [error, setError] = useState(''); const navigate = useNavigate()
  function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const title = form.get('title').trim(); const description = form.get('description').trim(); if (!title || !description) return setError('Please add an issue title and description.'); const now = new Date(); const id = `CM-${Date.now().toString().slice(-6)}`; const commonArea = form.get('commonArea'); const location = [form.get('block') && `Block ${form.get('block')}`, form.get('floor') && `Floor ${form.get('floor')}`, form.get('flat') && `Flat ${form.get('flat')}`, commonArea].filter(Boolean).join(', ') || 'Society premises'; const issue = { id, title, description, category: form.get('category'), priority: form.get('priority'), status: 'Open', location, block: form.get('block'), floor: form.get('floor'), flat: form.get('flat'), commonArea, reporterId: currentUser.id, reporter: currentUser.name, assignedTo: '', assignedName: '', createdAt: now.toISOString(), date: formatDate(now), photoName: form.get('photo').name || '', resolutionNote: '', statusHistory: [{ status: 'Open', by: currentUser.name, date: formatDateTime(now) }] }; saveIssues([issue, ...getIssues()]); navigate('/resident/issues') }
  return <AppLayout><div className="mx-auto max-w-3xl"><h1 className="text-3xl font-bold text-slate-900">Report an Issue</h1><p className="mt-2 text-slate-600">Share a concern and our team will follow up.</p><form onSubmit={submit} className="mt-7 grid gap-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Field label="Issue Title"><input name="title" className={input} required /></Field><Field label="Description"><textarea name="description" className={input} rows="4" required /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Category"><select name="category" className={input} required><option value="">Select category</option>{categories.map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Priority"><select name="priority" className={input} defaultValue="Medium"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></Field></div><div className="grid gap-5 sm:grid-cols-3"><Field label="Block"><input name="block" className={input} /></Field><Field label="Floor"><input name="floor" className={input} /></Field><Field label="Flat Number"><input name="flat" className={input} /></Field></div><Field label="Common Area"><input name="commonArea" className={input} placeholder="e.g. Garden, lobby, parking" /></Field><Field label="Photo (optional)"><input name="photo" className="text-sm" type="file" accept="image/*" /></Field><button className="rounded-lg bg-emerald-700 px-4 py-3 font-bold text-white hover:bg-emerald-800">Submit Issue</button></form></div></AppLayout>
}
function Field({ label, children }) { return <label className="grid gap-2 text-sm font-bold text-slate-700"><span>{label}</span>{children}</label> }
export default ReportIssue
